import {
  AlertTriangle,
  Award,
  Baby,
  Banknote,
  Briefcase,
  Building2,
  Calculator,
  CalendarClock,
  CheckCircle2,
  ClipboardCheck,
  Clock,
  Cpu,
  FileSignature,
  FileText,
  Gavel,
  GraduationCap,
  HandCoins,
  HeartHandshake,
  Hospital,
  Landmark,
  Laptop,
  Lock,
  Megaphone,
  Moon,
  PiggyBank,
  Scale,
  Scroll,
  ShieldCheck,
  ShoppingBag,
  Stethoscope,
  Target,
  Truck,
  Users,
  UserCheck,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const icons = {
  alert: AlertTriangle,
  award: Award,
  baby: Baby,
  banknote: Banknote,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  calendar: CalendarClock,
  check: CheckCircle2,
  clipboard: ClipboardCheck,
  clock: Clock,
  contract: FileSignature,
  cpu: Cpu,
  document: FileText,
  gavel: Gavel,
  graduation: GraduationCap,
  hands: HeartHandshake,
  hospital: Hospital,
  landmark: Landmark,
  laptop: Laptop,
  lock: Lock,
  megaphone: Megaphone,
  moon: Moon,
  money: HandCoins,
  pension: PiggyBank,
  scale: Scale,
  scroll: Scroll,
  shield: ShieldCheck,
  shop: ShoppingBag,
  stethoscope: Stethoscope,
  target: Target,
  truck: Truck,
  users: Users,
  userCheck: UserCheck,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, className }: { name: IconName; className?: string }) {
  const Component = icons[name];
  return <Component className={className} aria-hidden />;
}
